name: Publish Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.zip
